namespace CarringtonMortgage.Models.InputCopyBookModels.MortgageLoanBillingModels
{
    public class TransactionRecordModel
    {
        public string Rssi_Rcd_Id { get; set; }
        public string Rssi_Inst { get; set; }
        public string Rssi_Acct_No { get; set; }
        public string Rssi_Seq_No { get; set; }
        public string Rssi_Log_Date_PackedData { get; set; }
        public string Rssi_Log_Time_PackedData { get; set; }
        public string Rssi_Tr_Date_PackedData { get; set; }
        public string Rssi_Log_Ptrn { get; set; }
        public string Rssi_Tr_Fill_01 { get; set; }
        public string Rssi_Log_Tran { get; set; }
        public string Rssi_Tr_Fill_02 { get; set; }
        public string Rssi_Tr_Store_Ovride { get; set; }
        public string Rssi_Tr_Fill_03 { get; set; }
        public string Rssi_Tr_Amt_PackedData { get; set; }
        public string Rssi_Tr_Cash_Amt_PackedData { get; set; }
        public string Rssi_Tr_Teller_PackedData { get; set; }
        public string Rssi_Tr_Unap_Cd_Before { get; set; }
        public string Rssi_Tr_Unap_Cd_After { get; set; }
        public string Rssi_Tr_Amt_To_Prin_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Int_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Esc_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Lc_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Pvar_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Ivar_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Evar_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Lvar_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Lip_PackedData { get; set; }
        public string Rssi_Tr_Pymt_Ctr_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Cr_Ins_PackedData { get; set; }
        public string Rssi_Tr_Prin_Bal_PackedData { get; set; }
        public string Rssi_Tr_Esc_Bal_PackedData { get; set; }
        public string Rssi_Tr_Pd_To_Date_PackedData { get; set; }
        public string Rssi_Tr_Esc_Pymt_PackedData { get; set; }
        public string Rssi_Tr_Prn_Var_PackedData { get; set; }
        public string Rssi_Tr_Uncoll_Int_PackedData { get; set; }
        public string Rssi_Tr_Esc_Var_PackedData { get; set; }
        public string Rssi_Tr_Uncoll_Lc_PackedData { get; set; }
        public string Rssi_Tr_Dla_PackedData { get; set; }
        public string Rssi_Tr_Lip_Bal_PackedData { get; set; }
        public string Rssi_Tr_Lip_La_Date_PackedData { get; set; }
        public string Rssi_Tr_Pre_Int_Amt_PackedData { get; set; }
        public string Rssi_Tr_Pre_Int_Date { get; set; }
        public string Rssi_Tr_Amt_To_Fees_PackedData { get; set; }
        public string Rssi_Tr_Fee_Code { get; set; }
        public string Rssi_Tr_Fee_Desc { get; set; }
        public string Rssi_Tr_Amt_Negam_Tak_PackedData { get; set; }
        public string Rssi_Tr_Amt_Negam_Pd_PackedData { get; set; }
        public string Rssi_Tr_Esc_Pay_Id { get; set; }
        public string Rssi_Tr_Amort_Fee_Pymt { get; set; }
        public string Rssi_Tr_Amt_To_Evar_2 { get; set; }
        public string Rssi_Tr_Amt_To_Evar_3 { get; set; }
        public string Rssi_Tr_Amt_To_Evar_4 { get; set; }
        public string Rssi_Tr_Amt_To_Evar_5 { get; set; }
        public string Rssi_Tr_Exp_Fee_Code { get; set; }
        public string Rssi_Tr_Exp_Fee_Desc { get; set; }
        public string Rssi_Tr_Exp_Fee_Amt_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Pi_Shrtg { get; set; }
        public string Rssi_Tr_Amt_To_Esc_Short { get; set; }
        public string Rssi_Tr_Amt_To_Acrd_Inctv { get; set; }
        public string Rssi_Tr_Amt_To_Pra_Remain { get; set; }
        public string Rssi_Tr_Amt_To_Def_Prin_PackedData { get; set; }
        public string Rssi_Tr_Def_Prin_Bal_After_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Def_Int_PackedData { get; set; }
        public string Rssi_Tr_Def_Int_Bal_Aft_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Def_Late_Chrg_PackedData { get; set; }
        public string Rssi_Tr_Def_Lt_Chg_Bal_Aft_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Def_Esc_Adv_PackedData { get; set; }
        public string Rssi_Tr_Def_Esc_Adv_Bal_Aft_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Def_Pd_Exp_Adv_PackedData { get; set; }
        public string Rssi_Tr_Def_Pd_Exp_Adv_Bal_Aft_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Def_Unp_Exp_Adv_PackedData { get; set; }
        public string Rssi_Tr_Def_Unpexp_Bal_Aft_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Def_Admin_Fees_PackedData { get; set; }
        public string Rssi_Tr_Def_Admin_Fees_Bal_Aft_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Def_Optins_PackedData { get; set; }
        public string Rssi_Tr_Def_Optins_Bal_Aft_PackedData { get; set; }
        public string Rssi_Tr_Amt_To_Esc_Nt_PackedData { get; set; }
        public string Filler_459_1500 { get; set; }
    }
}
