using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ODHS_EDelivery.Models.InputCopyBookModels.MortgageLoanBillingModels
{
   public class UserFieldRecordModel
    {
        public string Rssi_Rcd_Id { get; set; }
        public string Rssi_Inst { get; set; }
        public string Rssi_Acct_No { get; set; }
        public string Rssi_Seq_No { get; set; }
        public string Rssi_Usr_02_PackedData { get; set; }
        public string Rssi_Usr_03 { get; set; }
        public string Rssi_Usr_04 { get; set; }
        public string Rssi_Usr_05 { get; set; }
        public string Rssi_Usr_06 { get; set; }
        public string Rssi_Usr_08 { get; set; }
        public string Rssi_Usr_09 { get; set; }
        public string Rssi_Usr_10 { get; set; }
        public string Rssi_Usr_11 { get; set; }
        public string Rssi_Usr_12 { get; set; }
        public string Rssi_Usr_13 { get; set; }
        public string Rssi_Usr_14 { get; set; }
        public string Rssi_Usr_15_PackedData { get; set; }
        public string Rssi_Usr_16_PackedData { get; set; }
        public string Rssi_Usr_17_PackedData { get; set; }
        public string Rssi_Usr_18 { get; set; }
        public string Rssi_Usr_19 { get; set; }
        public string Rssi_Usr_20_PackedData { get; set; }
        public string Rssi_Usr_21 { get; set; }
        public string Rssi_Usr_22 { get; set; }
        public string Rssi_Usr_23 { get; set; }
        public string Rssi_Usr_24 { get; set; }
        public string Rssi_Usr_25_PackedData { get; set; }
        public string Rssi_Usr_26_PackedData { get; set; }
        public string Rssi_Usr_27_PackedData { get; set; }
        public string Rssi_Usr_28_PackedData { get; set; }
        public string Rssi_Usr_29_PackedData { get; set; }
        public string Rssi_Usr_30_PackedData { get; set; }
        public string Rssi_Usr_31_PackedData { get; set; }
        public string Rssi_Usr_32_PackedData { get; set; }
        public string Rssi_Usr_33_PackedData { get; set; }
        public string Rssi_Usr_34_PackedData { get; set; }
        public string Rssi_Usr_35 { get; set; }
        public string Rssi_Usr_37 { get; set; }
        public string Rssi_Usr_38 { get; set; }
        public string Rssi_Usr_39 { get; set; }
        public string Rssi_Usr_40 { get; set; }
        public string Rssi_Usr_41 { get; set; }
        public string Rssi_Usr_42 { get; set; }
        public string Rssi_Usr_43 { get; set; }
        public string Rssi_Usr_44 { get; set; }
        public string Rssi_Usr_45 { get; set; }
        public string Rssi_Usr_46 { get; set; }
        public string Rssi_Usr_47 { get; set; }
        public string Rssi_Usr_48 { get; set; }
        public string Rssi_Usr_49 { get; set; }
        public string Rssi_Usr_50 { get; set; }
        public string Rssi_Usr_51 { get; set; }
        public string Rssi_Usr_52 { get; set; }
        public string Rssi_Usr_53 { get; set; }
        public string Rssi_Usr_54 { get; set; }
        public string Rssi_Usr_55 { get; set; }
        public string Rssi_Usr_56 { get; set; }
        public string Rssi_Usr_57 { get; set; }
        public string Rssi_Usr_58 { get; set; }
        public string Rssi_Usr_59 { get; set; }
        public string Rssi_Usr_60 { get; set; }
        public string Rssi_Usr_61 { get; set; }
        public string Rssi_Usr_62 { get; set; }
        public string Rssi_Usr_63 { get; set; }
        public string Rssi_Usr_64 { get; set; }
        public string Rssi_Usr_65 { get; set; }
        public string Rssi_Usr_66 { get; set; }
        public string Rssi_Usr_67 { get; set; }
        public string Rssi_Usr_68 { get; set; }
        public string Rssi_Usr_69 { get; set; }
        public string Rssi_Usr_70 { get; set; }
        public string Rssi_Usr_71 { get; set; }
        public string Rssi_Usr_72 { get; set; }
        public string Rssi_Usr_73 { get; set; }
        public string Rssi_Usr_74 { get; set; }
        public string Rssi_Usr_75 { get; set; }
        public string Rssi_Usr_76 { get; set; }
        public string Rssi_Usr_77 { get; set; }
        public string Rssi_Usr_78 { get; set; }
        public string Rssi_Usr_79 { get; set; }
        public string Rssi_Usr_80 { get; set; }
        public string Rssi_Usr_81 { get; set; }
        public string Rssi_Usr_82 { get; set; }
        public string Rssi_Usr_83 { get; set; }
        public string Rssi_Usr_84 { get; set; }
        public string Rssi_Usr_85 { get; set; }
        public string Rssi_Usr_86 { get; set; }
        public string Rssi_Usr_87 { get; set; }
        public string Rssi_Usr_88 { get; set; }
        public string Rssi_Usr_89 { get; set; }
        public string Rssi_Usr_90 { get; set; }
        public string Rssi_Usr_91 { get; set; }
        public string Rssi_Usr_92 { get; set; }
        public string Rssi_Usr_93 { get; set; }
        public string Rssi_Usr_94 { get; set; }
        public string Rssi_Usr_95 { get; set; }
        public string Rssi_Usr_96 { get; set; }
        public string Rssi_Usr_97 { get; set; }
        public string Rssi_Usr_98 { get; set; }
        public string Rssi_Usr_99 { get; set; }
        public string Rssi_Usr_100 { get; set; }
        public string Rssi_Usr_101 { get; set; }
        public string Rssi_Usr_102 { get; set; }
        public string Rssi_Usr_103 { get; set; }
        public string Rssi_Usr_104 { get; set; }
        public string Rssi_Usr_105 { get; set; }
        public string Rssi_Usr_106 { get; set; }
        public string Rssi_Usr_107 { get; set; }
        public string Rssi_Usr_108 { get; set; }
        public string Rssi_Usr_109 { get; set; }
        public string Rssi_Usr_110 { get; set; }
        public string Rssi_Usr_111 { get; set; }
        public string Rssi_Usr_112 { get; set; }
        public string Rssi_Usr_113 { get; set; }
        public string Rssi_Usr_114 { get; set; }
        public string Rssi_Usr_115 { get; set; }
        public string Rssi_Usr_116 { get; set; }
        public string Rssi_Usr_117 { get; set; }
        public string Rssi_Usr_118 { get; set; }
        public string Rssi_Usr_119 { get; set; }
        public string Rssi_Usr_120 { get; set; }
        public string Rssi_Usr_121 { get; set; }
        public string Rssi_Usr_122 { get; set; }
        public string Rssi_Usr_123 { get; set; }
        public string Rssi_Usr_124 { get; set; }
        public string Rssi_Usr_125 { get; set; }
        public string Rssi_Usr_126 { get; set; }
        public string Rssi_Usr_127 { get; set; }
        public string Rssi_Usr_128 { get; set; }
        public string Rssi_Usr_129 { get; set; }
        public string Rssi_Usr_130 { get; set; }
        public string Rssi_Usr_131 { get; set; }
        public string Rssi_Usr_132 { get; set; }
        public string Rssi_Usr_133 { get; set; }
        public string Rssi_Usr_134 { get; set; }
        public string Rssi_Usr_135 { get; set; }
        public string Rssi_Usr_136 { get; set; }
        public string Rssi_Usr_137 { get; set; }
        public string Rssi_Usr_138 { get; set; }
        public string Rssi_Usr_139 { get; set; }
        public string Rssi_Usr_140 { get; set; }
        public string Rssi_Usr_141 { get; set; }
        public string Rssi_Usr_142 { get; set; }
        public string Rssi_Usr_143 { get; set; }
        public string Rssi_Usr_144 { get; set; }
        public string Rssi_Usr_145 { get; set; }
        public string Rssi_Usr_146 { get; set; }
        public string Rssi_Usr_147 { get; set; }
        public string Rssi_Usr_148 { get; set; }
        public string Rssi_Usr_149 { get; set; }
        public string Rssi_Usr_150 { get; set; }
        public string Rssi_Usr_151 { get; set; }
        public string Rssi_Usr_152 { get; set; }
        public string Rssi_Usr_153 { get; set; }
        public string Rssi_Usr_154 { get; set; }
        public string Rssi_Usr_155 { get; set; }
        public string Rssi_Usr_156 { get; set; }
        public string Rssi_Usr_157 { get; set; }
        public string Rssi_Usr_158 { get; set; }
        public string Rssi_Usr_159 { get; set; }
        public string Rssi_Usr_160 { get; set; }
        public string Rssi_Usr_161 { get; set; }
        public string Rssi_Usr_162 { get; set; }
        public string Rssi_Usr_163 { get; set; }
        public string Rssi_Usr_164 { get; set; }
        public string Rssi_Usr_165 { get; set; }
        public string Rssi_Usr_166 { get; set; }
        public string Rssi_Usr_167 { get; set; }
        public string Rssi_Usr_168 { get; set; }
        public string Rssi_Usr_169 { get; set; }
        public string Rssi_Usr_170 { get; set; }
        public string Rssi_Usr_171 { get; set; }
        public string Rssi_Usr_172 { get; set; }
        public string Rssi_Usr_173 { get; set; }
        public string Rssi_Usr_174 { get; set; }
        public string Rssi_Usr_175 { get; set; }
        public string Rssi_Usr_176 { get; set; }
        public string Rssi_Usr_177 { get; set; }
        public string Rssi_Usr_178 { get; set; }
        public string Rssi_Usr_179 { get; set; }
        public string Rssi_Usr_180 { get; set; }
        public string Rssi_Usr_181 { get; set; }
        public string Rssi_Usr_182 { get; set; }
        public string Rssi_Usr_183 { get; set; }
        public string Rssi_Usr_184 { get; set; }
        public string Rssi_Usr_185 { get; set; }
        public string Rssi_Usr_186 { get; set; }
        public string Rssi_Usr_187 { get; set; }
        public string Rssi_Usr_188 { get; set; }
        public string Rssi_Usr_189 { get; set; }
        public string Rssi_Usr_190 { get; set; }
        public string Rssi_Usr_191 { get; set; }
        public string Rssi_Usr_192 { get; set; }
        public string Rssi_Usr_193 { get; set; }
        public string Rssi_Usr_194 { get; set; }
        public string Rssi_Usr_195 { get; set; }
        public string Rssi_Usr_196 { get; set; }
        public string Rssi_Usr_197 { get; set; }
        public string Rssi_Usr_198 { get; set; }
        public string Rssi_Usr_199 { get; set; }
        public string Rssi_Usr_200 { get; set; }
        public string Rssi_Usr_201 { get; set; }
        public string Rssi_Usr_202 { get; set; }
        public string Rssi_Usr_203 { get; set; }
        public string Rssi_Usr_204 { get; set; }
        public string Rssi_Usr_205 { get; set; }
        public string Rssi_Usr_206 { get; set; }
        public string Rssi_Usr_207 { get; set; }
        public string Rssi_Usr_208 { get; set; }
        public string Rssi_Usr_209 { get; set; }
        public string Rssi_Usr_210 { get; set; }
        public string Rssi_Usr_211 { get; set; }
        public string Rssi_Usr_212 { get; set; }
        public string Rssi_Usr_213 { get; set; }
        public string Rssi_Usr_214 { get; set; }
        public string Rssi_Usr_215_PackedData { get; set; }
        public string Rssi_Usr_216_PackedData { get; set; }
        public string Rssi_Usr_217_PackedData { get; set; }
        public string Rssi_Usr_218_PackedData { get; set; }
        public string Rssi_Usr_219_PackedData { get; set; }
        public string Rssi_Usr_220_PackedData { get; set; }
        public string Rssi_Usr_221_PackedData { get; set; }
        public string Rssi_Usr_222_PackedData { get; set; }
        public string Rssi_Usr_223_PackedData { get; set; }
        public string Rssi_Usr_224_PackedData { get; set; }
        public string Rssi_Usr_225_PackedData { get; set; }
        public string Rssi_Usr_226_PackedData { get; set; }
        public string Rssi_Usr_227_PackedData { get; set; }
        public string Rssi_Usr_228_PackedData { get; set; }
        public string Rssi_Usr_229_PackedData { get; set; }
        public string Rssi_Usr_230_PackedData { get; set; }
        public string Rssi_Usr_231_PackedData { get; set; }
        public string Rssi_Usr_232_PackedData { get; set; }
        public string Rssi_Usr_233_PackedData { get; set; }
        public string Rssi_Usr_234_PackedData { get; set; }
        public string Rssi_Usr_235_PackedData { get; set; }
        public string Rssi_Usr_236_PackedData { get; set; }
        public string Rssi_Usr_237_PackedData { get; set; }
        public string Rssi_Usr_238_PackedData { get; set; }
        public string Rssi_Usr_239_PackedData { get; set; }
        public string Rssi_Usr_240_PackedData { get; set; }
        public string Rssi_Usr_241_PackedData { get; set; }
        public string Rssi_Usr_242_PackedData { get; set; }
        public string Rssi_Usr_243_PackedData { get; set; }
        public string Rssi_Usr_244_PackedData { get; set; }
        public string Rssi_Usr_245_PackedData { get; set; }
        public string Rssi_Usr_246_PackedData { get; set; }
        public string Rssi_Usr_247_PackedData { get; set; }
        public string Rssi_Usr_248_PackedData { get; set; }
        public string Rssi_Usr_249_PackedData { get; set; }
        public string Rssi_Usr_250_PackedData { get; set; }
        public string Rssi_Usr_251_PackedData { get; set; }
        public string Rssi_Usr_252_PackedData { get; set; }
        public string Rssi_Usr_253_PackedData { get; set; }
        public string Rssi_Usr_254_PackedData { get; set; }
        public string Rssi_Usr_255_PackedData { get; set; }
        public string Rssi_Usr_256_PackedData { get; set; }
        public string Rssi_Usr_257_PackedData { get; set; }
        public string Rssi_Usr_258_PackedData { get; set; }
        public string Rssi_Usr_259_PackedData { get; set; }
        public string Rssi_Usr_260_PackedData { get; set; }
        public string Rssi_Usr_261_PackedData { get; set; }
        public string Rssi_Usr_262_PackedData { get; set; }
        public string Rssi_Usr_263_PackedData { get; set; }
        public string Rssi_Usr_264_PackedData { get; set; }
        public string Rssi_Usr_265_PackedData { get; set; }
        public string Rssi_Usr_266_PackedData { get; set; }
        public string Rssi_Usr_267_PackedData { get; set; }
        public string Rssi_Usr_268_PackedData { get; set; }
        public string Rssi_Usr_269_PackedData { get; set; }
        public string Rssi_Usr_270_PackedData { get; set; }
        public string Rssi_Usr_271_PackedData { get; set; }
        public string Rssi_Usr_272_PackedData { get; set; }
        public string Rssi_Usr_273_PackedData { get; set; }
        public string Rssi_Usr_274_PackedData { get; set; }
        public string Rssi_Usr_275_PackedData { get; set; }
        public string Rssi_Usr_276_PackedData { get; set; }
        public string Rssi_Usr_277_PackedData { get; set; }
        public string Rssi_Usr_278_PackedData { get; set; }
        public string Rssi_Usr_279_PackedData { get; set; }
        public string Rssi_Usr_280_PackedData { get; set; }
        public string Rssi_Usr_281_PackedData { get; set; }
        public string Rssi_Usr_282_PackedData { get; set; }
        public string Rssi_Usr_283_PackedData { get; set; }
        public string Rssi_Usr_284_PackedData { get; set; }
        public string Rssi_Usr_285_PackedData { get; set; }
        public string Rssi_Usr_286_PackedData { get; set; }
        public string Rssi_Usr_287_PackedData { get; set; }
        public string Rssi_Usr_288_PackedData { get; set; }
        public string Rssi_Usr_289_PackedData { get; set; }
        public string Rssi_Usr_290_PackedData { get; set; }
        public string Rssi_Usr_291_PackedData { get; set; }
        public string Rssi_Usr_292_PackedData { get; set; }
        public string Rssi_Usr_293_PackedData { get; set; }
        public string Rssi_Usr_294_PackedData { get; set; }
        public string Rssi_Usr_295_PackedData { get; set; }
        public string Rssi_Usr_296_PackedData { get; set; }
        public string Rssi_Usr_297_PackedData { get; set; }
        public string Rssi_Usr_298_PackedData { get; set; }
        public string Rssi_Usr_299_PackedData { get; set; }
        public string Rssi_Usr_300_PackedData { get; set; }
        public string Rssi_Usr_301_PackedData { get; set; }
        public string Rssi_Usr_302_PackedData { get; set; }
        public string Rssi_Usr_303_PackedData { get; set; }
        public string Rssi_Usr_304_PackedData { get; set; }
        public string Rssi_Usr_305_PackedData { get; set; }
        public string Rssi_Usr_306_PackedData { get; set; }
        public string Rssi_Usr_307_PackedData { get; set; }
        public string Rssi_Usr_308_PackedData { get; set; }
        public string Rssi_Usr_309_PackedData { get; set; }
        public string Rssi_Usr_310_PackedData { get; set; }
        public string Rssi_Usr_311_PackedData { get; set; }
        public string Rssi_Usr_312_PackedData { get; set; }
        public string Rssi_Usr_313_PackedData { get; set; }
        public string Rssi_Usr_314_PackedData { get; set; }
        public string Rssi_Usr_315_PackedData { get; set; }
        public string Rssi_Usr_316_PackedData { get; set; }
        public string Rssi_Usr_317_PackedData { get; set; }
        public string Rssi_Usr_318_PackedData { get; set; }
        public string Rssi_Usr_319_PackedData { get; set; }
        public string Rssi_Usr_320_PackedData { get; set; }
        public string Rssi_Usr_321_PackedData { get; set; }
        public string Rssi_Usr_322_PackedData { get; set; }
        public string Rssi_Usr_323_PackedData { get; set; }
        public string Rssi_Usr_324_PackedData { get; set; }
        public string Rssi_Usr_325_PackedData { get; set; }
        public string Rssi_Usr_326_PackedData { get; set; }
        public string Rssi_Usr_327_PackedData { get; set; }
        public string Rssi_Usr_328_PackedData { get; set; }
        public string Rssi_Usr_329_PackedData { get; set; }
        public string Rssi_Usr_330_PackedData { get; set; }
        public string Rssi_Usr_331_PackedData { get; set; }
        public string Rssi_Usr_332_PackedData { get; set; }
        public string Rssi_Usr_333_PackedData { get; set; }
        public string Rssi_Usr_334_PackedData { get; set; }
        public string Rssi_Usr_335_PackedData { get; set; }
        public string Rssi_Usr_336_PackedData { get; set; }
        public string Rssi_Usr_337_PackedData { get; set; }
        public string Rssi_Usr_338_PackedData { get; set; }
        public string Rssi_Usr_339_PackedData { get; set; }
        public string Rssi_Usr_340_PackedData { get; set; }
        public string Rssi_Usr_341_PackedData { get; set; }
        public string Rssi_Usr_342_PackedData { get; set; }
        public string Rssi_Usr_343_PackedData { get; set; }
        public string Rssi_Usr_344_PackedData { get; set; }
        public string Rssi_Usr_345_PackedData { get; set; }
        public string Rssi_Usr_346_PackedData { get; set; }
        public string Rssi_Usr_347_PackedData { get; set; }
        public string Rssi_Usr_348_PackedData { get; set; }
        public string Rssi_Usr_349_PackedData { get; set; }
        public string Rssi_Usr_350_PackedData { get; set; }
        public string Rssi_Usr_351_PackedData { get; set; }
        public string Rssi_Usr_352_PackedData { get; set; }
        public string Rssi_Usr_353_PackedData { get; set; }
        public string Rssi_Usr_354_PackedData { get; set; }
        public string Rssi_Usr_355_PackedData { get; set; }
        public string Rssi_Usr_356_PackedData { get; set; }
        public string Rssi_Usr_357_PackedData { get; set; }
        public string Rssi_Usr_358_PackedData { get; set; }
        public string Rssi_Usr_359_PackedData { get; set; }
        public string Rssi_Usr_360_PackedData { get; set; }
        public string Rssi_Usr_361_PackedData { get; set; }
        public string Rssi_Usr_362_PackedData { get; set; }
        public string Rssi_Usr_363_PackedData { get; set; }
        public string Rssi_Usr_364_PackedData { get; set; }
        public string Rssi_Usr_365_PackedData { get; set; }
        public string Rssi_Usr_366_PackedData { get; set; }
        public string Rssi_Usr_367_PackedData { get; set; }
        public string Rssi_Usr_368_PackedData { get; set; }
        public string Rssi_Usr_369_PackedData { get; set; }
        public string Rssi_Usr_370_PackedData { get; set; }
        public string Rssi_Usr_371_PackedData { get; set; }
        public string Rssi_Usr_372_PackedData { get; set; }
        public string Rssi_Usr_373_PackedData { get; set; }
        public string FillerPart3 { get; set; }

    }
}
