using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ODHS_EDelivery.Models.InputCopyBookModels.MortgageLoanBillingModels
{
   public class UserFieldRecordModel
    {
        public string RecordIdentifier { get; set; }
        public string InstitutionNumber { get; set; }
        public string AccountNumber { get; set; }
        public string SequenceNumber { get; set; }
        public string UserField02 { get; set; }
        public string UserField03 { get; set; }
        public string UserField04 { get; set; }
        public string UserField05 { get; set; }
        public string UserField06 { get; set; }
        public string UserField08 { get; set; }
        public string UserField09 { get; set; }
        public string UserField10 { get; set; }
        public string UserField11 { get; set; }
        public string UserField12 { get; set; }
        public string UserField13 { get; set; }
        public string UserField14 { get; set; }
        public string UserField15 { get; set; }
        public string UserField16 { get; set; }
        public string UserField17 { get; set; }
        public string UserField18 { get; set; }
        public string UserField19 { get; set; }
        public string UserField20 { get; set; }
        public string UserField21 { get; set; }
        public string UserField22 { get; set; }
        public string UserField23 { get; set; }
        public string UserField24 { get; set; }
        public string UserField25 { get; set; }
        public string UserField26 { get; set; }
        public string UserField27 { get; set; }
        public string UserField28 { get; set; }
        public string UserField29 { get; set; }
        public string UserField30 { get; set; }
        public string UserField31 { get; set; }
        public string UserField32 { get; set; }
        public string UserField33 { get; set; }
        public string UserField34 { get; set; }
        public string UserField35 { get; set; }
        public string UserField37 { get; set; }
        public string UserField38 { get; set; }
        public string UserField39 { get; set; }
        public string UserField40 { get; set; }
        public string UserField41 { get; set; }
        public string UserField42 { get; set; }
        public string UserField43 { get; set; }
        public string UserField44 { get; set; }
        public string UserField45 { get; set; }
        public string UserField46 { get; set; }
        public string UserField47 { get; set; }
        public string UserField48 { get; set; }
        public string UserField49 { get; set; }
        public string UserField50 { get; set; }
        public string UserField51 { get; set; }
        public string UserField52 { get; set; }
        public string UserField53 { get; set; }
        public string UserField54 { get; set; }
        public string UserField55 { get; set; }
        public string UserField56 { get; set; }
        public string UserField57 { get; set; }
        public string UserField58 { get; set; }
        public string UserField59 { get; set; }
        public string UserField60 { get; set; }
        public string UserField61 { get; set; }
        public string UserField62 { get; set; }
        public string UserField63 { get; set; }
        public string UserField64 { get; set; }
        public string UserField65 { get; set; }
        public string UserField66 { get; set; }
        public string UserField67 { get; set; }
        public string UserField68 { get; set; }
        public string UserField69 { get; set; }
        public string UserField70 { get; set; }
        public string UserField71 { get; set; }
        public string UserField72 { get; set; }
        public string UserField73 { get; set; }
        public string UserField74 { get; set; }
        public string UserField75 { get; set; }
        public string UserField76 { get; set; }
        public string UserField77 { get; set; }
        public string UserField78 { get; set; }
        public string UserField79 { get; set; }
        public string UserField80 { get; set; }
        public string UserField81 { get; set; }
        public string UserField82 { get; set; }
        public string UserField83 { get; set; }
        public string UserField84 { get; set; }
        public string UserField85 { get; set; }
        public string UserField86 { get; set; }
        public string UserField87 { get; set; }
        public string UserField88 { get; set; }
        public string UserField89 { get; set; }
        public string UserField90 { get; set; }
        public string UserField91 { get; set; }
        public string UserField92 { get; set; }
        public string UserField93 { get; set; }
        public string UserField94 { get; set; }
        public string UserField95 { get; set; }
        public string UserField96 { get; set; }
        public string UserField97 { get; set; }
        public string UserField98 { get; set; }
        public string UserField99 { get; set; }
        public string UserField100 { get; set; }
        public string UserField101 { get; set; }
        public string UserField102 { get; set; }
        public string UserField103 { get; set; }
        public string UserField104 { get; set; }
        public string UserField105 { get; set; }
        public string UserField106 { get; set; }
        public string UserField107 { get; set; }
        public string UserField108 { get; set; }
        public string UserField109 { get; set; }
        public string UserField110 { get; set; }
        public string UserField111 { get; set; }
        public string UserField112 { get; set; }
        public string UserField113 { get; set; }
        public string UserField114 { get; set; }
        public string UserField115 { get; set; }
        public string UserField116 { get; set; }
        public string UserField117 { get; set; }
        public string UserField118 { get; set; }
        public string UserField119 { get; set; }
        public string UserField120 { get; set; }
        public string UserField121 { get; set; }
        public string UserField122 { get; set; }
        public string UserField123 { get; set; }
        public string UserField124 { get; set; }
        public string UserField125 { get; set; }
        public string UserField126 { get; set; }
        public string UserField127 { get; set; }
        public string UserField128 { get; set; }
        public string UserField129 { get; set; }
        public string UserField130 { get; set; }
        public string UserField131 { get; set; }
        public string UserField132 { get; set; }
        public string UserField133 { get; set; }
        public string UserField134 { get; set; }
        public string UserField135 { get; set; }
        public string UserField136 { get; set; }
        public string UserField137 { get; set; }
        public string UserField138 { get; set; }
        public string UserField139 { get; set; }
        public string UserField140 { get; set; }
        public string UserField141 { get; set; }
        public string UserField142 { get; set; }
        public string UserField143 { get; set; }
        public string UserField144 { get; set; }
        public string UserField145 { get; set; }
        public string UserField146 { get; set; }
        public string UserField147 { get; set; }
        public string UserField148 { get; set; }
        public string UserField149 { get; set; }
        public string UserField150 { get; set; }
        public string UserField151 { get; set; }
        public string UserField152 { get; set; }
        public string UserField153 { get; set; }
        public string UserField154 { get; set; }
        public string UserField155 { get; set; }
        public string UserField156 { get; set; }
        public string UserField157 { get; set; }
        public string UserField158 { get; set; }
        public string UserField159 { get; set; }
        public string UserField160 { get; set; }
        public string UserField161 { get; set; }
        public string UserField162 { get; set; }
        public string UserField163 { get; set; }
        public string UserField164 { get; set; }
        public string UserField165 { get; set; }
        public string UserField166 { get; set; }
        public string UserField167 { get; set; }
        public string UserField168 { get; set; }
        public string UserField169 { get; set; }
        public string UserField170 { get; set; }
        public string UserField171 { get; set; }
        public string UserField172 { get; set; }
        public string UserField173 { get; set; }
        public string UserField174 { get; set; }
        public string UserField175 { get; set; }
        public string UserField176 { get; set; }
        public string UserField177 { get; set; }
        public string UserField178 { get; set; }
        public string UserField179 { get; set; }
        public string UserField180 { get; set; }
        public string UserField181 { get; set; }
        public string UserField182 { get; set; }
        public string UserField183 { get; set; }
        public string UserField184 { get; set; }
        public string UserField185 { get; set; }
        public string UserField186 { get; set; }
        public string UserField187 { get; set; }
        public string UserField188 { get; set; }
        public string UserField189 { get; set; }
        public string UserField190 { get; set; }
        public string UserField191 { get; set; }
        public string UserField192 { get; set; }
        public string UserField193 { get; set; }
        public string UserField194 { get; set; }
        public string UserField195 { get; set; }
        public string UserField196 { get; set; }
        public string UserField197 { get; set; }
        public string UserField198 { get; set; }
        public string UserField199 { get; set; }
        public string UserField200 { get; set; }
        public string UserField201 { get; set; }
        public string UserField202 { get; set; }
        public string UserField203 { get; set; }
        public string UserField204 { get; set; }
        public string UserField205 { get; set; }
        public string UserField206 { get; set; }
        public string UserField207 { get; set; }
        public string UserField208 { get; set; }
        public string UserField209 { get; set; }
        public string UserField210 { get; set; }
        public string UserField211 { get; set; }
        public string UserField212 { get; set; }
        public string UserField213 { get; set; }
        public string UserField214 { get; set; }
        public string UserField215 { get; set; }
        public string UserField216 { get; set; }
        public string UserField217 { get; set; }
        public string UserField218 { get; set; }
        public string UserField219 { get; set; }
        public string UserField220 { get; set; }
        public string UserField221 { get; set; }
        public string UserField222 { get; set; }
        public string UserField223 { get; set; }
        public string UserField224 { get; set; }
        public string UserField225 { get; set; }
        public string UserField226 { get; set; }
        public string UserField227 { get; set; }
        public string UserField228 { get; set; }
        public string UserField229 { get; set; }
        public string UserField230 { get; set; }
        public string UserField231 { get; set; }
        public string UserField232 { get; set; }
        public string UserField233 { get; set; }
        public string UserField234 { get; set; }
        public string UserField235 { get; set; }
        public string UserField236 { get; set; }
        public string UserField237 { get; set; }
        public string UserField238 { get; set; }
        public string UserField239 { get; set; }
        public string UserField240 { get; set; }
        public string UserField241 { get; set; }
        public string UserField242 { get; set; }
        public string UserField243 { get; set; }
        public string UserField244 { get; set; }
        public string UserField245 { get; set; }
        public string UserField246 { get; set; }
        public string UserField247 { get; set; }
        public string UserField248 { get; set; }
        public string UserField249 { get; set; }
        public string UserField250 { get; set; }
        public string UserField251 { get; set; }
        public string UserField252 { get; set; }
        public string UserField253 { get; set; }
        public string UserField254 { get; set; }
        public string UserField255 { get; set; }
        public string UserField256 { get; set; }
        public string UserField257 { get; set; }
        public string UserField258 { get; set; }
        public string UserField259 { get; set; }
        public string UserField260 { get; set; }
        public string UserField261 { get; set; }
        public string UserField262 { get; set; }
        public string UserField263 { get; set; }
        public string UserField264 { get; set; }
        public string UserField265 { get; set; }
        public string UserField266 { get; set; }
        public string UserField267 { get; set; }
        public string UserField268 { get; set; }
        public string UserField269 { get; set; }
        public string UserField270 { get; set; }
        public string UserField271 { get; set; }
        public string UserField272 { get; set; }
        public string UserField273 { get; set; }
        public string UserField274 { get; set; }
        public string UserField275 { get; set; }
        public string UserField276 { get; set; }
        public string UserField277 { get; set; }
        public string UserField278 { get; set; }
        public string UserField279 { get; set; }
        public string UserField280 { get; set; }
        public string UserField281 { get; set; }
        public string UserField282 { get; set; }
        public string UserField283 { get; set; }
        public string UserField284 { get; set; }
        public string UserField285 { get; set; }
        public string UserField286 { get; set; }
        public string UserField287 { get; set; }
        public string UserField288 { get; set; }
        public string UserField289 { get; set; }
        public string UserField290 { get; set; }
        public string UserField291 { get; set; }
        public string UserField292 { get; set; }
        public string UserField293 { get; set; }
        public string UserField294 { get; set; }
        public string UserField295 { get; set; }
        public string UserField296 { get; set; }
        public string UserField297 { get; set; }
        public string UserField298 { get; set; }
        public string UserField299 { get; set; }
        public string UserField300 { get; set; }
        public string UserField301 { get; set; }
        public string UserField302 { get; set; }
        public string UserField303 { get; set; }
        public string UserField304 { get; set; }
        public string UserField305 { get; set; }
        public string UserField306 { get; set; }
        public string UserField307 { get; set; }
        public string UserField308 { get; set; }
        public string UserField309 { get; set; }
        public string UserField310 { get; set; }
        public string UserField311 { get; set; }
        public string UserField312 { get; set; }
        public string UserField313 { get; set; }
        public string UserField314 { get; set; }
        public string UserField315 { get; set; }
        public string UserField316 { get; set; }
        public string UserField317 { get; set; }
        public string UserField318 { get; set; }
        public string UserField319 { get; set; }
        public string UserField320 { get; set; }
        public string UserField321 { get; set; }
        public string UserField322 { get; set; }
        public string UserField323 { get; set; }
        public string UserField324 { get; set; }
        public string UserField325 { get; set; }
        public string UserField326 { get; set; }
        public string UserField327 { get; set; }
        public string UserField328 { get; set; }
        public string UserField329 { get; set; }
        public string UserField330 { get; set; }
        public string UserField331 { get; set; }
        public string UserField332 { get; set; }
        public string UserField333 { get; set; }
        public string UserField334 { get; set; }
        public string UserField335 { get; set; }
        public string UserField336 { get; set; }
        public string UserField337 { get; set; }
        public string UserField338 { get; set; }
        public string UserField339 { get; set; }
        public string UserField340 { get; set; }
        public string UserField341 { get; set; }
        public string UserField342 { get; set; }
        public string UserField343 { get; set; }
        public string UserField344 { get; set; }
        public string UserField345 { get; set; }
        public string UserField346 { get; set; }
        public string UserField347 { get; set; }
        public string UserField348 { get; set; }
        public string UserField349 { get; set; }
        public string UserField350 { get; set; }
        public string UserField351 { get; set; }
        public string UserField352 { get; set; }
        public string UserField353 { get; set; }
        public string UserField354 { get; set; }
        public string UserField355 { get; set; }
        public string UserField356 { get; set; }
        public string UserField357 { get; set; }
        public string UserField358 { get; set; }
        public string UserField359 { get; set; }
        public string UserField360 { get; set; }
        public string UserField361 { get; set; }
        public string UserField362 { get; set; }
        public string UserField363 { get; set; }
        public string UserField364 { get; set; }
        public string UserField365 { get; set; }
        public string UserField366 { get; set; }
        public string UserField367 { get; set; }
        public string UserField368 { get; set; }
        public string UserField369 { get; set; }
        public string UserField370 { get; set; }
        public string UserField371 { get; set; }
        public string UserField372 { get; set; }
        public string UserField373 { get; set; }
        public string FillerPart3 { get; set; }

    }
}
